# App
spring.application.name=driver-tracker
server.port=8080

# Redis
spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Rate limit
ratelimit.driver.updates-per-second=1
ratelimit.global.requests-per-minute=60